### ISSUE TITLE
Response code 401

### ISSUE THREAD

**Issue by freakyfreaky** [hombach/ioBroker.kostal-piko-ba#373]
**Describe the bug**  
I am using a PIKO 5.5 because we our system is now 10 yrs old.
After setting up everything I get an error messag

ERROR:
Error in calling Kostal Piko API: HTTPError: Response code 401 (Unauthorized)

**To Reproduce**  
1. Set up Instance
2. Wait for first poll

**Versions:**  
 - Adapter version: 1.5.0
 - Node version: 16.17.1
 - Operating system: raspberry pi & ubuntu 22

**Comment by hombach** [comment]
Any logs in debug mode? Or perhaps you send your IP to check in sentry logs...

**Comment by freakyfreaky** [comment]
DEBUG LOG

**Comment by hombach** [comment]
Hard to tell without direct access to your system, but as far as I understood you'll need an Kostal UI => 6.11.
There is an update to Version 6.41 for your inverter on the Kostal Homepage. Perhaps also an FW Update could be usefull.
Which version of UI and firmware are you using?

**Comment by freakyfreaky** [comment]
A very old one. :)
It is a Piko 5.5 with version 3.75
According first Google result there is no update option for this old buddy

Don’t worry too much if there is no way arround.  I will script something as I did with my old PHP setup. I just wanted to give the adapter a try on a non supported version to test it for you. 

![42A499CE-6B8A-470E-9712-B4CB28E4CCF9](https://user-images.githubusercontent.com/8963666/195258806-6dc6b4e5-0782-424e-8a91-cc1ccdd7850b.jpeg)

**Comment by freakyfreaky** [comment]
![46D18334-D43C-4402-9734-BB828F958F0B](https://user-jimages.githubusercontent.com/8963666/195259032-b562a5b4-74c2-452c-8472-56ec6eff7d04.jpeg)

**Comment by freakyfreaky** [comment]
![Uploading 640DEC32-1C4B-4723-ACB0-A01F39ECB0B2.jpeg…]()

**Comment by hombach** [comment]
Are you sure there is no new firmware available? Because of HW version? By a short check in sentry there have been using 14 PIKO 5.5 owners the adapter in the past few days (without error) UI v6.11; v6.20; v6.30 and v6.41

**Comment by hombach** [comment]
Looks like there has been v4 released in summer 2011... as initial version. Perhaps new hardware at the same date?https://www.kostal-solar-electric.com/de-de/download/archiv/#Solar-Wechselrichter/PIKO%204.2%20-%208.5/Deutschland/Update/
