### ISSUE TITLE
KOSTAL PIKO 4.2

### ISSUE THREAD

**Issue by TomsEleven** [hombach/ioBroker.kostal-piko-ba#383]
Hallo,

vielen Dank erstmal fürs Programmieren des Adapters. Du wolltest wissen, ob auch andere der genannten Modelle funktionieren und momentan funktioniert mein PIKO 4.2 leider nicht.

Node.js: v14.20.1   ///   NPM: 6.14.17   ///   Adapter 2.0.0   ///   Linux VM

Nach Eingabe der IP-Adresse des WR wird der Adapter "grün" liefert allerdings keine Werte und zeigt Folgendes Log:

kostal-piko-ba.0 | 2022-11-07 11:55:36.079 | error | Please verify IP address: 192.168.178.32 !! (e4)
kostal-piko-ba.0 | 2022-11-07 11:55:36.079 | error | Error in calling Kostal Piko API for total statistics: HTTPError: Response code 401 (Unauthorized)
kostal-piko-ba.0 | 2022-11-07 11:55:36.006 | info | Polltime alltime statistics set to: 200 seconds
kostal-piko-ba.0 | 2022-11-07 11:55:36.006 | info | Polltime daily statistics set to: 60 seconds
kostal-piko-ba.0 | 2022-11-07 11:55:36.005 | info | Polltime set to: 10 seconds

Vll muss ich noch was einstellen, da er offensichtlich keine Verbindung über die API aufbauen kann.

Viele Grüße
Tom

**Comment by hombach** [comment]
Hallo Tom,

"und momentan funktioniert mein PIKO 4.2 leider nicht." ....  D.h. er hat einmal funktioniert? Die Fehlermeldung sagt meist wenn die Firmware des Umrichters zu alt ist. Der Adapter konnte die UI-Version auch nicht auslesen. 
Welche Inverter-UI hast Du da auf der Maschine?
PS: Es gibt mehrere PIKO 4.2 auf denen es funktioniert.

**Comment by TomsEleven** [comment]
Hi,
sorry. Falsch formuliert: bei mir funktionierts nicht. Liegt bestimmt an der Firmware. Ich habe 3.77

Habs jetzt mit dem Parser Adapter gelöst.

Vielen Dank & viele Grüße
Tom

![Kostal](https://user-images.githubusercontent.com/117567938/200633164-f19490a8-6103-4da6-949b-8652b9e26c1f.jpg)

**Comment by hombach** [comment]
ja, das ist zu alt, sorry
