### ISSUE TITLE
Keine Daten von Piko 3.0-1 MP plus

### ISSUE THREAD

**Issue by Dirkules1979** [hombach/ioBroker.kostal-piko-ba#415]
Hallo Christian,

ich arbeite mich gerade in IOBroker ein und bin dabei über deinen Adapter für den Kostal Piko gestossen, vielen Dank dafür.
Hab mir dann nachdem die Version im IOBroker (2.1.1) keine Daten geliefert hat , per Github die Ver. 2.2.0 installiert.
Leider bekomme ich in der Objektansicht auch keine Daten vom Wechselrichter angezeigt. Die Instanz laüft und ist grün.
Neuestes Update ist auch auf dem Wechselrichter installiert. 
Muss ich am Wechselrichter selbst irgendwas umstellen ?

Könntest du mir hier vielleicht behilflich sein eine Lösung zu finden ?

Viele Grüße

Dirk

**Comment by Dirkules1979** [comment]
Habe grad den Beitrag von Gernot gelesen, er hat ja anscheinend Daten vom Wechselrichter...

**Comment by Dirkules1979** [comment]
Wow das ging flott, ok dann solltest du mir noch erklären wie ich an die LOG-Daten komme.
Habe schonmal im IOBroker den Kostal-Adapter mit Häkchen bei Debug-Mode installiert.

Sentry ? SOrry ich bin Neuling...kann ich da was tun ? 

Mit externener Stromsensor meinst du das Smart Energy Meter, oder ? Nein hängt zwar im Verteilerschrank ist aber noch überhaupt nicht verdrahtet. Also nur der reine Wechselrichter ist in Betrieb.

**Comment by hombach** [comment]
... ich war zu ungeduldig... Sentry Meldung von Dir vermutlich da. Ist deine Inverter IP 192.168.188.68?

**Comment by Dirkules1979** [comment]
Ja genau

**Comment by hombach** [comment]
Sentry meldet Fehler des Adapters anonymisiert an ein Cloud Portal. Damit kann ich Fehler finden ohne dass sich jemand meldet - wie Du eben. Dabei werden ein paar unkritische Daten mit weitergegeben - wie z.B. die eingetragene IP - damit kann ich hier dann eine Zuordnung machen.
_This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers. For more details and for informations on how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0._

**Comment by Dirkules1979** [comment]
So sieht´s übrigens in den Protokollen aus:

kostal-piko-ba.0 | 2023-02-06 21:28:46.875 | error | Please verify IP address: 192.168.188.68 !! (e2)
-- | -- | -- | --
kostal-piko-ba.0 | 2023-02-06 21:28:46.875 | error | Error in calling Kostal Piko API: HTTPError: Response code 404 (Not found)

**Comment by hombach** [comment]
![image](https://user-images.githubusercontent.com/63002482/217078370-8408975a-fdfb-48b6-9c13-68486b100510.png)

Sagt Sentry über deinen Versuch..... Keine auslesbare Firmware-Version und Typ des Umrichters. Hört sich auch nach Neuanlage an? Sprich neuer Umrichter?

Ich denke das ist dann der falsche Adapter für deine Zwecke. Dein Umrichter sollte von der neueren Plenticore bzw. Plus Generation sein - der hat eine komplett andere Schnittstelle. Sprich du hast einen "Piko MP Plus 3"?Wenn ja, versuch doch mal den Adapter "KOSTAL Plenticore Plus"....

**Comment by Dirkules1979** [comment]
Keine Neuanlage...ist von ca. 2018 oder so, haben das Haus erst kürzlich so gekauft.
Das sagt die Info direkt auf dem WR:



Name | PIKO 3.0-1 MP plus
-- | --


Hier die SW-Version vom Wechselrichter:


0 | HMI BFAPI STM32F4 | 2.8.0
-- | -- | --
1 | HMI FBL | 1.4.0
2 | HMI APP | 3.18.0
3 | HMI OEM PIKO 3.0-1 MP p | 1.0.1
4 | PU BFAPI SAFE STM32F4 | 2.8.0
5 | PU FBL | 2.0.3
6 | PU APP | 4.7.0
7 | PU PAR default | 24.0.24
8 | PU OEM VAR_8_Kostal | 1.0.7
9 | ENS1 APP | 1.35.0

**Comment by hombach** [comment]
ja... MP Plus ... die Umstellung der Geräte war 2018 ;)
so ungefähr?
![image](https://user-images.githubusercontent.com/63002482/217081400-c84ff792-7604-4b1b-9efd-044dae32e4fc.png)

-> Adapter "KOSTAL Plenticore Plus" könnte klappen

**Comment by Dirkules1979** [comment]
Genauso...
Hab grad den Plenticore-Adapter installiert...keine Verbindung zu Gerät.

**Comment by hombach** [comment]
Das ist schade.... evtl. bekommst Du dort noch weitere Infos? 
Bist ja nicht der erste mit dem "Problem" dass die Hardware zu neu ist... LOL evtl. müsste ich doch mal versuchen den Adapter zu erweitern.

**Comment by Dirkules1979** [comment]
Also ich habe große Hoffnung in dich... ;-)

**Comment by hombach** [comment]
FYI _"Habe grad den Beitrag von Gernot gelesen, er hat ja anscheinend Daten vom Wechselrichter..."_
Gernot hat den alten Piko 3.0 - ohne MP Plus

**Comment by Dirkules1979** [comment]
Achso ok...

**Comment by hombach** [comment]
Versuch mal http://192.168.188.68/api/v1

**Comment by Dirkules1979** [comment]
Seite wurde nicht gefunden

**Comment by hombach** [comment]
Kommt von https://www.photovoltaikforum.com/thread/136824-rest-api-f%C3%BCr-kostal-pleticore-wechselrichter/

**Comment by hombach** [comment]
Die sprechen aber immer alle vom Plenticore... Sollte da ein größerer Unterschied sein? .... Hast Du mal bei KOSTAL nach der Doku der Modbus TCP Schnittstelle gesucht?

**Comment by hombach** [comment]
file:///C:/Users/chris/AppData/Local/Temp/MicrosoftEdgeDownloads/028c76e1-3ceb-48f9-90a8-63dc85f6fdf9/[BA-Protocol_PIKO-MP-plus_en.pdf](file:///C:/Users/chris/AppData/Local/Temp/MicrosoftEdgeDownloads/028c76e1-3ceb-48f9-90a8-63dc85f6fdf9/BA-Protocol_PIKO-MP-plus_en.pdf)

**Comment by Dirkules1979** [comment]
Du meinst sowas:
https://www.kostal-solar-electric.com/de-de/download/download/-/media/document-library-folder---kse/2021/02/17/15/19/ba-protocol_piko-mp-plus_en.pdf

**Comment by hombach** [comment]
Bringt  http://192.168.188.68/measurements.xml   ein Ergebnis?

**Comment by hombach** [comment]
Das ist ein wenig arg klein.... ;)
http://192.168.188.68/versions.xml   ???

**Comment by hombach** [comment]
Ok... hätte ich mal gezoomed ....  Ich kann dir also jetzt damit sagen dass bei euch akut keine Sonne scheint :)

**Comment by Dirkules1979** [comment]
![image](https://user-images.githubusercontent.com/124625908/217089340-04324130-0a3b-483e-a3c3-a8cdbd3e9065.png)

**Comment by Dirkules1979** [comment]
Ich hab den ersten Screenshot sicherheitshalber gelöscht wegen Ser. Nr., sorry.

Ich hoffe immer noch das du damit jetzt was anfangen kannst... :-)

**Comment by hombach** [comment]
Ich sags mal so... anfangen kann man damit was. 
Eigentlich wollte ich bei einer kleinen Anlagen Erweiterung letzten Sommer auch noch einen Piko 2.0 MP Plus zusätzlich einbauen... Dann könnte der Adapter das heute schon.
Das Teil war aber nicht lieferbar, daher habe ich das auf den zweiten Eingang meines Piko 6.0 BA angehängt. Und siehe da - der kommt nicht nur mit deutlich kleinerer Startspannung wie im Datenblatte zurecht - er kann auch dauerhaft über 7KW liefern, nicht nur 6KW (evtl. ein umgelabelter Piko 8.0 BA??)
Daher ist das jetzt auch so geblieben - deutlich Geld gespart.

**Comment by hombach** [comment]
... mit dem Parser Adapter könntest Du dir da evtl. auch helfen.

**Comment by hombach** [comment]
Kannst Du mir bitte den Output von ...verison.xml mal als Text hier rein stellen.... würde da bei Gelegenheit mal was probieren.

**Comment by Dirkules1979** [comment]
> ... mit dem Parser Adapter könntest Du dir da evtl. auch helfen.

???

**Comment by Dirkules1979** [comment]
<root>
<Device Name="PIKO 3.0-1 MP plus" Type="Inverter" Platform="Net16" HmiPlatform="HMI17" NominalPower="3000" UserPowerLimit="nan" CountryPowerLimit="nan" Serial="XXXXXXXXXXXXXXXXXXXX" OEMSerial="XXXXXXXX" BusAddress="1" NetBiosName="INV007034470001" WebPortal="PIKO Solar Portal" ManufacturerURL="kostal-solar-electric.com" IpAddress="192.168.188.68" DateTime="2023-02-06T22:33:29" MilliSeconds="355">
<Versions>
<Software Device="HMI" Name="BFAPI STM32F4" Version="2.8.0"/>
<Software Device="HMI" Name="FBL" Version="1.4.0"/>
<Software Device="HMI" Name="APP" Version="3.18.0"/>
<Software Device="HMI" Name="OEM PIKO 3.0-1 MP p" Version="1.0.1"/>
<Software Device="PU" Name="BFAPI SAFE STM32F4" Version="2.8.0"/>
<Software Device="PU" Name="FBL" Version="2.0.3"/>
<Software Device="PU" Name="APP" Version="4.7.0"/>
<Software Device="PU" Name="PAR default" Version="24.0.24"/>
<Software Device="PU" Name="OEM VAR_8_Kostal" Version="1.0.7"/>
<Software Device="ENS1" Name="APP" Version="1.35.0"/>
<Hardware Device="HMI" Version="1"/>
<Hardware Device="PU" Version="5"/>
</Versions>
</Device>
</root>

**Comment by Dirkules1979** [comment]
[PIKO3.0 MP plus.txt](https://github.com/hombach/ioBroker.kostal-piko-ba/files/10669367/PIKO3.0.MP.plus.txt)

Hab die Ser. Nr. unkenntlich gemacht...

**Comment by hombach** [comment]
Hallo Dirk, sofern noch von Interesse - ich habe zumindest die Erkennung der Piko MP API implementiert.... du solltest in der 2.3.0 zumindest eine Meldung im Log bekommen welchen Typ du hast und dass dieser noch nicht unterstützt wird.... ;)
More to follow ;)
-> Feedback deinerseits wäre hilfreich

**Comment by Dirkules1979** [comment]
Ok ich schau es später mal an und werde berichten.

**Comment by Dirkules1979** [comment]
Ok also was neu ist, dass wenn ich unter "Objekte" - "kostal-piko-ba" - "0" - "info" gehe sehe ich bei "Inverter Type" den Typ meines Wechselrichters, dies war vorher nicht der Fall meine ich.

Hast du das gemeint mit der Meldung im Log ?

**Comment by hombach** [comment]
Das, und in Protokolle sollte ein Error auftauchen: "Piko MP API not supported yet!!!!" 
Das hat schon mal funktioniert, super.

Wenn du mir jetzt noch mal die Text-Ausgabe  von  [http://192.168.188.68/measurements.xml](http://192.168.188.68/measurements.xml) hier reinstellen könntest.... Idealerweise irgendwann wenn etwas Sonne scheint.

**Comment by Dirkules1979** [comment]
Ok mach ich sobald die Sonne scheint.

**Comment by Dirkules1979** [comment]
Es kommen aktuell grad nur 380W rein, aber ich hoffe das reicht.
Nachfolgend der gewünschte Text (Serial und OEM Serial hab ich wieder unkenntlich gemacht)

<root>
<Device Name="PIKO 3.0-1 MP plus" Type="Inverter" Platform="Net16" HmiPlatform="HMI17" NominalPower="3000" UserPowerLimit="nan" CountryPowerLimit="nan" Serial="XXXXXXXXXX" OEMSerial="XXXXXXX" BusAddress="1" NetBiosName="INV007034470001" WebPortal="PIKO Solar Portal" ManufacturerURL="kostal-solar-electric.com" IpAddress="192.168.188.68" DateTime="2023-02-27T15:28:41" MilliSeconds="873">
<Measurements>
<Measurement Value="226.2" Unit="V" Type="AC_Voltage"/>
<Measurement Value="1.645" Unit="A" Type="AC_Current"/>
<Measurement Value="381.6" Unit="W" Type="AC_Power"/>
<Measurement Value="374.2" Unit="W" Type="AC_Power_fast"/>
<Measurement Value="50.000" Unit="Hz" Type="AC_Frequency"/>
<Measurement Value="344.9" Unit="V" Type="DC_Voltage"/>
<Measurement Value="1.214" Unit="A" Type="DC_Current"/>
<Measurement Value="343.3" Unit="V" Type="LINK_Voltage"/>
<Measurement Unit="W" Type="GridPower"/>
<Measurement Unit="W" Type="GridConsumedPower"/>
<Measurement Unit="W" Type="GridInjectedPower"/>
<Measurement Unit="W" Type="OwnConsumedPower"/>
<Measurement Value="100.0" Unit="%" Type="Derating"/>
</Measurements>
</Device>
</root>

**Comment by Dirkules1979** [comment]
<root>
<Device Name="PIKO 3.0-1 MP plus" Type="Inverter" Platform="Net16" HmiPlatform="HMI17" NominalPower="3000" UserPowerLimit="nan" CountryPowerLimit="nan" Serial="763167EJ007034470001" OEMSerial="10351314" BusAddress="1" NetBiosName="INV007034470001" WebPortal="PIKO Solar Portal" ManufacturerURL="kostal-solar-electric.com" IpAddress="192.168.188.68" DateTime="2023-02-27T15:28:41" MilliSeconds="873">
<Measurements>
<Measurement Value="226.2" Unit="V" Type="AC_Voltage"/>
<Measurement Value="1.645" Unit="A" Type="AC_Current"/>
<Measurement Value="381.6" Unit="W" Type="AC_Power"/>
<Measurement Value="374.2" Unit="W" Type="AC_Power_fast"/>
<Measurement Value="50.000" Unit="Hz" Type="AC_Frequency"/>
<Measurement Value="344.9" Unit="V" Type="DC_Voltage"/>
<Measurement Value="1.214" Unit="A" Type="DC_Current"/>
<Measurement Value="343.3" Unit="V" Type="LINK_Voltage"/>
<Measurement Unit="W" Type="GridPower"/>
<Measurement Unit="W" Type="GridConsumedPower"/>
<Measurement Unit="W" Type="GridInjectedPower"/>
<Measurement Unit="W" Type="OwnConsumedPower"/>
<Measurement Value="100.0" Unit="%" Type="Derating"/>
</Measurements>
</Device>
</root>

**Comment by Dirkules1979** [comment]
<root>
<Device Name="PIKO 3.0-1 MP plus" Type="Inverter" Platform="Net16" HmiPlatform="HMI17" NominalPower="3000" UserPowerLimit="nan" CountryPowerLimit="nan" Serial="763167EJ007034470001" OEMSerial="10351314" BusAddress="1" NetBiosName="INV007034470001" WebPortal="PIKO Solar Portal" ManufacturerURL="kostal-solar-electric.com" IpAddress="192.168.188.68" DateTime="2023-02-27T15:28:41" MilliSeconds="873">
<Measurements>
<Measurement Value="226.2" Unit="V" Type="AC_Voltage"/>
<Measurement Value="1.645" Unit="A" Type="AC_Current"/>
<Measurement Value="381.6" Unit="W" Type="AC_Power"/>
<Measurement Value="374.2" Unit="W" Type="AC_Power_fast"/>
<Measurement Value="50.000" Unit="Hz" Type="AC_Frequency"/>
<Measurement Value="344.9" Unit="V" Type="DC_Voltage"/>
<Measurement Value="1.214" Unit="A" Type="DC_Current"/>
<Measurement Value="343.3" Unit="V" Type="LINK_Voltage"/>
<Measurement Unit="W" Type="GridPower"/>
<Measurement Unit="W" Type="GridConsumedPower"/>
<Measurement Unit="W" Type="GridInjectedPower"/>
<Measurement Unit="W" Type="OwnConsumedPower"/>
<Measurement Value="100.0" Unit="%" Type="Derating"/>
</Measurements>
</Device>
</root>

**Comment by Dirkules1979** [comment]
<root>
<Device Name="PIKO 3.0-1 MP plus" Type="Inverter" Platform="Net16" HmiPlatform="HMI17" NominalPower="3000" UserPowerLimit="nan" CountryPowerLimit="nan" Serial="763167EJ007034470001" OEMSerial="10351314" BusAddress="1" NetBiosName="INV007034470001" WebPortal="PIKO Solar Portal" ManufacturerURL="[kostal-solar-electric.com](http://kostal-solar-electric.com/)" IpAddress="192.168.188.68" DateTime="2023-02-27T15:28:41" MilliSeconds="873">
<Measurements>
<Measurement Value="226.2" Unit="V" Type="AC_Voltage"/>
<Measurement Value="1.645" Unit="A" Type="AC_Current"/>
<Measurement Value="381.6" Unit="W" Type="AC_Power"/>
<Measurement Value="374.2" Unit="W" Type="AC_Power_fast"/>
<Measurement Value="50.000" Unit="Hz" Type="AC_Frequency"/>
<Measurement Value="344.9" Unit="V" Type="DC_Voltage"/>
<Measurement Value="1.214" Unit="A" Type="DC_Current"/>
<Measurement Value="343.3" Unit="V" Type="LINK_Voltage"/>
<Measurement Unit="W" Type="GridPower"/>
<Measurement Unit="W" Type="GridConsumedPower"/>
<Measurement Unit="W" Type="GridInjectedPower"/>
<Measurement Unit="W" Type="OwnConsumedPower"/>
<Measurement Value="100.0" Unit="%" Type="Derating"/>
</Measurements>
</Device>
</root>

**Comment by Dirkules1979** [comment]
Kommen zwar aktuell nur ca. 280W rein aber ich hoffe das passt so...

<root>

<Device Name="PIKO 3.0-1 MP plus" Type="Inverter" Platform="Net16" HmiPlatform="HMI17" NominalPower="3000" UserPowerLimit="nan" CountryPowerLimit="nan" Serial=„XXXXXXXX" OEMSerial=„XXXXXXX“ BusAddress="1" NetBiosName="INV007034470001" WebPortal="PIKO Solar Portal" ManufacturerURL="[kostal-solar-electric.com](http://kostal-solar-electric.com/)" IpAddress="192.168.188.68" DateTime="2023-02-27T15:28:41" MilliSeconds="873">

<Measurements>

<Measurement Value="226.2" Unit="V" Type="AC_Voltage"/>

<Measurement Value="1.645" Unit="A" Type="AC_Current"/>

<Measurement Value="381.6" Unit="W" Type="AC_Power"/>

<Measurement Value="374.2" Unit="W" Type="AC_Power_fast"/>

<Measurement Value="50.000" Unit="Hz" Type="AC_Frequency"/>

<Measurement Value="344.9" Unit="V" Type="DC_Voltage"/>

<Measurement Value="1.214" Unit="A" Type="DC_Current"/>

<Measurement Value="343.3" Unit="V" Type="LINK_Voltage"/>

<Measurement Unit="W" Type="GridPower"/>

<Measurement Unit="W" Type="GridConsumedPower"/>

<Measurement Unit="W" Type="GridInjectedPower"/>

<Measurement Unit="W" Type="OwnConsumedPower"/>

<Measurement Value="100.0" Unit="%" Type="Derating"/>

</Measurements>

</Device>

</root>

**Comment by Dirkules1979** [comment]
So jetzt aber...ich hoffe das passt so...

[PIKO3.0-1 MP plus.txt](https://github.com/hombach/ioBroker.kostal-piko-ba/files/10840864/PIKO3.0-1.MP.plus.txt)

**Comment by Dirkules1979** [comment]
<root>
<Device Name="PIKO 3.0-1 MP plus" Type="Inverter" Platform="Net16" HmiPlatform="HMI17" NominalPower="3000" UserPowerLimit="nan" CountryPowerLimit="nan" Serial="763167EJ007034470001" OEMSerial="10351314" BusAddress="1" NetBiosName="INV007034470001" WebPortal="PIKO Solar Portal" ManufacturerURL="kostal-solar-electric.com" IpAddress="192.168.188.68" DateTime="2023-02-27T15:50:27" MilliSeconds="889">
<Measurements>
<Measurement Value="226.5" Unit="V" Type="AC_Voltage"/>
<Measurement Value="1.071" Unit="A" Type="AC_Current"/>
<Measurement Value="244.9" Unit="W" Type="AC_Power"/>
<Measurement Value="243.4" Unit="W" Type="AC_Power_fast"/>
<Measurement Value="49.995" Unit="Hz" Type="AC_Frequency"/>
<Measurement Value="338.4" Unit="V" Type="DC_Voltage"/>
<Measurement Value="0.827" Unit="A" Type="DC_Current"/>
<Measurement Value="368.3" Unit="V" Type="LINK_Voltage"/>
<Measurement Unit="W" Type="GridPower"/>
<Measurement Unit="W" Type="GridConsumedPower"/>
<Measurement Unit="W" Type="GridInjectedPower"/>
<Measurement Unit="W" Type="OwnConsumedPower"/>
<Measurement Value="100.0" Unit="%" Type="Derating"/>
</Measurements>
</Device>
</root>

**Comment by hombach** [comment]
Hi Dirk, habe eben Version 2.4.0 hier in GitHub eingestellt... ohne Gerät zum Testen alles etwas wagen, aber bei Dir sollten nun die 3 Werte für DC1 ausgelesen werden. Bitte einmal testen, wenn du magst ;)

**Comment by Dirkules1979** [comment]
> Hi Dirk, habe eben Version 2.4.0 hier in GitHub eingestellt... ohne Gerät zum Testen alles etwas wagen, aber bei Dir sollten nun die 3 Werte für DC1 ausgelesen werden. Bitte einmal testen, wenn du magst ;)

Hallo Christian,

hab die neueste Version installiert und ja es werden für DC1 die Werte für Spannung und Strom ausgegeben aber bei der Leistung steht nur **(null)W**

![image](https://user-images.githubusercontent.com/124625908/223142969-e6a92410-1cf0-4aeb-81cf-39088266dd34.jpeg)

**Comment by hombach** [comment]
Hi Dirk, fixed - dummer Fehler. Die 2.4.0 ist in ein paar Stunden auch im Beta repository und unterstützt nun auch die AC Werte deines MP plus

**Comment by Dirkules1979** [comment]
> Hi Dirk, fixed - dummer Fehler. Die 2.4.0 ist in ein paar Stunden auch im Beta repository und unterstützt nun auch die AC Werte deines MP plus

Ok prima, danke. 
Ich werde es morgen nach der Arbeit testen und berichten. 👍🏻

**Comment by Dirkules1979** [comment]
Hallo Christian, 
funktioniert soweit, bis auf den Strom bei AC1. Siehe Screenshot ![image](https://user-images.githubusercontent.com/124625908/223467356-9dc12c83-d844-48d9-b046-ddb903de0b6a.jpeg)

**Comment by hombach** [comment]
OOPS - Rundungsfehler... fixxed.
In der 2.4.2 wird auch noch der Gesamtertrag der Inverters ausgelesen.

**Comment by Dirkules1979** [comment]
> OOPS - Rundungsfehler... fixxed.
> 
> In der 2.4.2 wird auch noch der Gesamtertrag der Inverters ausgelesen. 

Schaue ich mir morgen an. 👍🏻😊

**Comment by Dirkules1979** [comment]
> OOPS - Rundungsfehler... fixxed.
> 
> In der 2.4.2 wird auch noch der Gesamtertrag der Inverters ausgelesen. 

Ja passt 👍🏻
Siehe Screenshot. ![image](https://user-images.githubusercontent.com/124625908/223754320-8a1dd108-ea15-4cdc-9586-293edc6c671f.jpeg)

**Comment by hombach** [comment]
Running in stable version
